site_name: MaaGFL 文档

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Advanced:
    - Virtual Monitor: advanced/01_virtual_monitor.md
  - Tutorial:
    - 快速开始: tutorial/getting_started.md
    - FAQ: tutorial/FAQ.md
    - Base:
      - Chess:
        - Luffberry Chess: tutorial/base/chess/luffberry_chess.md
    - Experience:
      - '8-1N': tutorial/experience/8-1N/8-1n.md
      - '13-4': tutorial/experience/13-4/13-4.md
      - Shattered Connexion: tutorial/experience/shattered_connexion/shattered_connexion.md
    - Rescue:
      - Dool:
        - Doll: tutorial/rescue/dool/doll.md
      - Equipment:
        - Equipment: tutorial/rescue/equipment/equipment.md
    - Resource:
      - Gray Zone: tutorial/resource/01_gray_zone.md
      - SKK Logistics: tutorial/resource/02_skk_logistics.md
      - Shattered Connexion: tutorial/resource/03_shattered_connexion.md
      - Alchemy: tutorial/resource/04_alchemy.md
      - BLM: tutorial/resource/05_blm.md
