site_name: MaaGF1 文档
site_url: https://maagf1.github.io/docs/
site_description: 少女前线PC端自动化项目文档
repo_url: https://github.com/MaaGF1/MaaGF1
repo_name: MaaGF1/MaaGF1
edit_uri: https://github.com/MaaGF1/docs/edit/main/

# 自定义CSS
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: zh
  logo: assets/pic/logo_256.png
  favicon: assets/pic/logo_256.png
  # 主题配色
  palette: 
    # 1. 浅色模式
    - scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: 黄区配色 (Dark Mode)
    # 2. 深色模式
    - scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: 白区配色 (Light Mode)
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MaaGF1/MaaGF1
      name: GitHub 仓库

# 目录结构
nav:
  - 首页: index.md
  - 常见问题: tutorial/FAQ.md
  - 资源获取:
    - 飞行棋: tutorial/base/chess/luffberry_chess.md
    - 灰域探查: tutorial/resource/01_gray_zone.md
    - 指挥官后勤: tutorial/resource/02_skk_logistics.md
    - 捡垃圾: tutorial/resource/03_shattered_connexion.md
    - 炼金: tutorial/resource/04_alchemy.md
    - 零元购: tutorial/resource/05_blm.md
  - 练级指南:
    - 13-4: tutorial/experience/13-4/13-4.md
    - 8-1N: tutorial/experience/8-1N/8-1n.md
    - 裂变链接练级: tutorial/experience/shattered_connexion/shattered_connexion.md
  - 救援打捞:
    - 人形救援: tutorial/rescue/doll/doll.md
    - 装备打捞: tutorial/rescue/equipment/equipment.md
  - 进阶指南:
    - 虚拟显示器: advanced/01_virtual_monitor.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html